import { type NextPage } from "next";
import Head from "next/head";
import { PokeListContainer } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PokeList</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col justify-center">
        <h1 className="my-5 text-center text-6xl font-bold">PokeList</h1>

        <PokeListContainer />
      </main>
    </>
  );
};

export default Home;
