import { type NextPage } from "next";
import Head from "next/head";
import { PokeListContainer } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PokeList</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>PokeList</h1>

        <PokeListContainer />
      </main>
    </>
  );
};

export default Home;
